// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3t5RD9bSALzCYh_BVrX4GulN3cDHeZ5U',
    appId: '1:55276436160:web:a1d46f5832297dc8fc8b25',
    messagingSenderId: '55276436160',
    projectId: 'vericonnect-6f5e2',
    authDomain: 'vericonnect-6f5e2.firebaseapp.com',
    storageBucket: 'vericonnect-6f5e2.firebasestorage.app',
    measurementId: 'G-TNF2YDPZWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAizL8tzcNRKp4WWDjiHYb11srAXYQvx7c',
    appId: '1:55276436160:android:b92c6311c5821261fc8b25',
    messagingSenderId: '55276436160',
    projectId: 'vericonnect-6f5e2',
    storageBucket: 'vericonnect-6f5e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9ZA_7IKM7ch5KwulNaE5u-iupArhZVZE',
    appId: '1:55276436160:ios:80551b3aba306707fc8b25',
    messagingSenderId: '55276436160',
    projectId: 'vericonnect-6f5e2',
    storageBucket: 'vericonnect-6f5e2.firebasestorage.app',
    iosBundleId: 'com.example.vericon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9ZA_7IKM7ch5KwulNaE5u-iupArhZVZE',
    appId: '1:55276436160:ios:80551b3aba306707fc8b25',
    messagingSenderId: '55276436160',
    projectId: 'vericonnect-6f5e2',
    storageBucket: 'vericonnect-6f5e2.firebasestorage.app',
    iosBundleId: 'com.example.vericon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3t5RD9bSALzCYh_BVrX4GulN3cDHeZ5U',
    appId: '1:55276436160:web:2b1997ca13dc3dc4fc8b25',
    messagingSenderId: '55276436160',
    projectId: 'vericonnect-6f5e2',
    authDomain: 'vericonnect-6f5e2.firebaseapp.com',
    storageBucket: 'vericonnect-6f5e2.firebasestorage.app',
    measurementId: 'G-TQNYVT9Q4K',
  );
}
